version: '3'
services:
  db:
    image: flowminder/flowdb:synthetic-data-latest
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_DB}
      - FM_PASSWORD=foo
      - API_PASSWORD=foo
    ports:
      - ${DB_PORT}:5432
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - data_volume_db:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-fm_redis}
    ports:
      - 6379:6379
volumes:
  data_volume_db:
